api/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users', views.ExecutionTCViewSet)


urlpatterns = [
#url(r'^$', views.index, name='index'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

axa_reports/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include("dashboard.urls")),
    url(r'^api/', include("api.urls")),
    url(r'^auth/', include("projectadmin.urls")),
    url(r'^executions/', include("executions.urls", namespace="executions")),
    url(r'^testplans/', include("testplans.urls", namespace="testplans")),
    url(r'^testscripts/', include("testscripts.urls", namespace="testscripts")),
    url(r'^testcases/', include("testcases.urls", namespace="testcases")),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

testcases/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<tc_id>[0-9]+)/$', views.detail, name='detail'),
]

testcases/models.py
from django.db import models

from testscripts.models import TestScript

# Create your models here.
class TestCase(models.Model):
    tc_id           = models.AutoField(primary_key=True)
    script_id       = models.ForeignKey(TestScript)
    tc_name         = models.CharField(max_length=200)
    owner           = models.CharField(max_length=200, blank=True, null=True)
    created_time    = models.DateTimeField(auto_now_add=True, auto_now=False)
    modified_time   = models.DateTimeField(auto_now_add=False, auto_now=True)
    active          = models.BooleanField(default='Yes')
    def __str__(self):
        return self.tc_name;

testcases/views.py
from django.shortcuts import render

from django.http import HttpResponse
from .models import TestCase

# Create your views here.
def index(request):
    latest_testcase_list = TestCase.objects.order_by('-created_time')[:5]
    context = {'title':'Test Cases','latest_testcase_list': latest_testcase_list}
    return render(request, "testcases/index.html", context)


def detail(request, script_id):
    return HttpResponse("You are seeing testcase %s " % script_id)

templates/testcases/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
	<h1>{{ title }}</h1><br/>
	<div class="table-responsive">
	<table class="table table-hover tablesorter" id="testCaseTable">
		<thead> 
	    <tr class="hoverable">
	    	<th>Edit</th>
	        <th>TestCase ID</th>
	        <th>TestCase Name</th>
	        <th>TestScript Name</th>
	        <th>Owner</th>
	        <th>Active</th>
	        <th>Created Time</th>
	    </tr>
	    </thead> 
	    {% for item in latest_testcase_list %}
	    <tr {% if item.active|stringformat:"s" != "True" %} class='warning' {% endif %}> 
   	        <td><a href="{% url 'testcases:detail' item.tc_id  %}">Edit</a></td>	      
	        <td>{{ item.tc_id }}</td>
	        <td>{{ item.tc_name }}</td>
	        <td>{{ item.script_id }}</td>
	        <td>{{ item.owner }}</td>
	        <td>{{ item.active }}</td>
	        <td>{{ item.created_time }}</td>
	    </tr>
	    {% endfor %}
	</table>
	</div>
{% endblock content %}


{% block footer-content %}
    <script src="{% static "js/jquery.tablesorter.min.js" %}"></script>
    <script type="text/javascript" >
    	$(document).ready(function() 
		    { 
		        $("#testCaseTable").tablesorter(); 
		    } 
		);
    </script>
{% endblock footer-content %}




	