api/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users', views.ExecutionTCViewSet)


urlpatterns = [
#url(r'^$', views.index, name='index'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

axa_reports/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include("dashboard.urls")),
    url(r'^api/', include("api.urls")),
    url(r'^auth/', include("projectadmin.urls")),
    url(r'^executions/', include("executions.urls", namespace="executions")),
    url(r'^testplans/', include("testplans.urls", namespace="testplans")),
    url(r'^testscripts/', include("testscripts.urls", namespace="testscripts")),
    url(r'^testcases/', include("testcases.urls", namespace="testcases")),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

testscripts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<script_id>[0-9]+)/$', views.detail, name='detail'),
]

testscripts/models.py
from django.db import models

from testplans.models import TestPlan

# Create your models here.
class TestScript(models.Model):
    script_id       = models.AutoField(primary_key=True)
    plan_id         = models.ForeignKey(TestPlan)
    script_name     = models.CharField(max_length=200)
    script_path     = models.CharField(max_length=2000, blank=True, null=True)
    owner           = models.CharField(max_length=200, blank=True, null=True)
    created_time    = models.DateTimeField(auto_now_add=True, auto_now=False)
    modified_time   = models.DateTimeField(auto_now_add=False, auto_now=True)
    active          = models.BooleanField(default='Yes')
    def __str__(self):
        return self.script_name;

testscripts/views.py
from django.shortcuts import render

from django.http import HttpResponse
from testscripts.models import TestScript

# Create your views here.
def index(request):
    latest_testscript_list = TestScript.objects.order_by('-created_time')[:5]
    context = {'title':'Test Scripts','latest_testscript_list': latest_testscript_list}
    return render(request, "testscripts/index.html", context)


def detail(request, script_id):
    return HttpResponse("You are seeing testscript %s " % script_id)

templates/testscripts/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
	<h1>{{ title }}</h1><br/>
	<div class="table-responsive">
	<table class="table table-hover tablesorter" id="testScriptTable">
		<thead> 
	    <tr class="hoverable">
	    	<th>Edit</th>
	        <th>TestScript ID</th>
	        <th>TestScript Name</th>
	        <th>TestPlan Name</th>
	        <th>Owner</th>
	        <th>Active</th>
	        <th>Created Time</th>
	    </tr>
	    </thead> 
	    {% for item in latest_testscript_list %}
	    <tr {% if item.active|stringformat:"s" != "True" %} class='warning' {% endif %}> 
   	        <td><a href="{% url 'testscripts:detail' item.script_id  %}">Edit</a></td>	      
	        <td>{{ item.script_id }}</td>
	        <td>{{ item.script_name }}</td>
	        <td>{{ item.plan_id }}</td>
	        <td>{{ item.owner }}</td>
	        <td>{{ item.active }}</td>
	        <td>{{ item.created_time }}</td>
	    </tr>
	    {% endfor %}
	</table>
	</div>
{% endblock content %}


{% block footer-content %}
    <script src="{% static "js/jquery.tablesorter.min.js" %}"></script>
    <script type="text/javascript" >
    	$(document).ready(function() 
		    { 
		        $("#testScriptTable").tablesorter(); 
		    } 
		);
    </script>
{% endblock footer-content %}




	