api/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users', views.ExecutionTCViewSet)


urlpatterns = [
#url(r'^$', views.index, name='index'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

axa_reports/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include("dashboard.urls")),
    url(r'^api/', include("api.urls")),
    url(r'^auth/', include("projectadmin.urls")),
    url(r'^executions/', include("executions.urls", namespace="executions")),
    url(r'^testplans/', include("testplans.urls", namespace="testplans")),
    url(r'^testscripts/', include("testscripts.urls", namespace="testscripts")),
    url(r'^testcases/', include("testcases.urls", namespace="testcases")),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

testplans/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<plan_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<plan_id>[0-9]+)/testscripts/$', views.showScripts, name='showScripts'),
]

testplans/models.py
from django.db import models

# Create your models here.
class TestPlan(models.Model):
    plan_id         = models.AutoField(primary_key=True)
    testplan_id     = models.CharField(max_length=50,blank=True, null=True)
    testplan_name   = models.CharField(max_length=200)
    owner           = models.CharField(max_length=200, blank=True, null=True)
    created_time    = models.DateTimeField(auto_now_add=True, auto_now=False)
    modified_time   = models.DateTimeField(auto_now_add=False, auto_now=True)
    active          = models.BooleanField(default='Yes')
    def __str__(self):
        return self.testplan_name;
    

testplans/views.py
from django.shortcuts import render

from django.http import HttpResponse
from .models import TestPlan

# Create your views here.
def index(request):
    latest_testplan_list = TestPlan.objects.order_by('-created_time')[:5]
    context = {'title':'Test Plans','latest_testplan_list': latest_testplan_list}
    return render(request, "testplans/index.html", context)

def detail(request, plan_id):
    return HttpResponse("You are seeing testplan %s " % plan_id)

def showScripts(request, plan_id):
    return HttpResponse("You are seeing scripts for testplan %s " % plan_id)

templates/testplans/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
	<button id="createTPBtn" class="btn btn-default pull-right">Create TestPlan</button>
	<h1>{{ title }}</h1><br/>
	<div class="table-responsive">
	<table class="table table-hover tablesorter" id="testPlanTable">
		<thead> 
	    <tr class="hoverable">
	    	<th>Edit</th>
	        <th>TestPlan ID</th>
	        <th>TestPlan Name</th>
	        <th>Owner</th>
	        <th>Active</th>
	        <th>Created Time</th>
	    </tr>
	    </thead> 
	    {% for item in latest_testplan_list %}
	    <tr {% if item.active|stringformat:"s" != "True" %} class='warning' {% endif %}> 
   	        <td><a href="{% url 'testplans:detail' item.plan_id  %}">Edit</a></td>	      
	        <td>{{ item.testplan_id }}</td>
	        <td>{{ item.testplan_name }}</td>
	        <td>{{ item.owner }}</td>
	        <td>{{ item.active }}</td>
	        <td>{{ item.created_time }}</td>
	    </tr>
	    {% endfor %}
	</table>
	</div>
{% endblock content %}


{% block footer-content %}
    <script src="{% static "js/jquery.tablesorter.min.js" %}"></script>
    <script type="text/javascript" >
    	$(document).ready(function() 
		    { 
		        $("#testPlanTable").tablesorter(); 
		    } 
		);
		
		$( "#createTPBtn" ).click(function() {
		  window.location.href = "{% url 'testplans:index' %}";
		});
    </script>
{% endblock footer-content %}




	