api/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users', views.ExecutionTCViewSet)


urlpatterns = [
#url(r'^$', views.index, name='index'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

axa_reports/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include("dashboard.urls")),
    url(r'^api/', include("api.urls")),
    url(r'^auth/', include("projectadmin.urls")),
    url(r'^executions/', include("executions.urls", namespace="executions")),
    url(r'^testplans/', include("testplans.urls", namespace="testplans")),
    url(r'^testscripts/', include("testscripts.urls", namespace="testscripts")),
    url(r'^testcases/', include("testcases.urls", namespace="testcases")),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^$', views.index, name='index'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Amal Bose (axatrikx)">
    <link rel="icon" href="{% static "img/favicon.ico" %}">

    <title>{{ title }}</title>

    <link href="{% static "css/style.css" %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/navbar-static-top.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
<nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">QA Dashboard</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'executions:index' %}">Executions</a></li>
            <li><a href="{% url 'testplans:index' %}">Test Plans</a></li>
            <li><a href="{% url 'testscripts:index' %}">Test Scripts</a></li>
            <li><a href="{% url 'testcases:index' %}">Test Cases</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
         {% if user.is_authenticated %}
         	<ul class="nav navbar-nav navbar-right">
				<li><a href="/auth/logout/">Logout</a></li>
			</ul>
		 {% else %}
          <form class="navbar-form navbar-right" method="post" action="/auth/login/">
      		{% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Sign In</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
				<li><a href="/auth/register/">Register</a></li>
			</ul>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>

   <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
        {% block content %} {% endblock content%}
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block footer-content %} {% endblock footer-content%}
  </body>
</html>